# Generated by Django 5.1.1 on 2024-12-02 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="subscription_plan",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="subscription_plan",
        ),
    ]
