# Generated by Django 5.1.1 on 2024-12-02 16:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
        ("shop", "0002_subscriptionplan_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="subscription_plan",
            field=models.ForeignKey(
                default=django.utils.timezone.now,
                on_delete=django.db.models.deletion.CASCADE,
                to="shop.subscriptionplan",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="recipe",
            name="subscription_plan",
            field=models.ForeignKey(
                default=django.utils.timezone.now,
                on_delete=django.db.models.deletion.CASCADE,
                to="shop.subscriptionplan",
            ),
            preserve_default=False,
        ),
    ]
