# Generated by Django 5.0.9 on 2024-11-27 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_alter_content_options_alter_module_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="students",
        ),
    ]
