# Generated by Django 5.1.1 on 2024-11-29 23:30

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="studentwork",
            old_name="video_url",
            new_name="link",
        ),
        migrations.AddField(
            model_name="studentwork",
            name="date",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="studentwork",
            name="title",
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="studentwork",
            name="video",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="uploads/videos/",
                validators=[django.core.validators.FileExtensionValidator(["mp4"])],
            ),
        ),
        migrations.AlterField(
            model_name="studentwork",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="uploads/files/",
                validators=[django.core.validators.FileExtensionValidator(["pdf"])],
            ),
        ),
        migrations.AlterField(
            model_name="studentwork",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="uploads/images/",
                validators=[django.core.validators.FileExtensionValidator(["png"])],
            ),
        ),
    ]
